name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build image
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: docker build --tag twitch-data-gui:latest .
      - name: Deploy to Github Package Registry
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: DataCollectApp
          DOCKER_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
          docker tag twitch-data-gui:latest docker.pkg.github.com/datacollectapp/twitch-data-gui/twitch-data-gui:latest
          docker push docker.pkg.github.com/datacollectapp/twitch-data-gui/twitch-data-gui:latest